# version: "3.8"

services:
  app1:
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env.development
    depends_on:
      - db
      - localstack
    networks:
      - app-network

  db:
    image: mysql:8.0
    env_file:
      - .env.development
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "28080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src1:/var/www/html
    depends_on:
      - app1
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
